### ISSUE TITLE
My heart canister wont craft

### ISSUE THREAD

**Issue by Animationking11** [GamerDuck123/LifeStealSMP#30]
Screenshot: https://cdn.e-z.host/e-zimagehosting/98996106-718c-4250-b7d1-e6e1f6ee0b4c/ngmuqkja.png

**Comment by Animationking11** [comment]
here is my config as a file because github is doing some weird stuff

https://mega.nz/file/AJpQEBaY#og9UY8M3c3fwypnVKbmemjuheYSWvy6ULn-7Yd_BijA

**Comment by GamerDuck123** [comment]
Was your plugin starting? I just pushed an update because I left some legacy code from testing that bricked the plugin from starting: https://github.com/GamerDuck123/LifeStealSMP/releases/tag/0.1.2-PATCH

Also for your config, I would change the characters that are mathematical characters, as sometimes java will freak out with that i.e + - and = should not be used

As well you have 2 conflicting items that are using the same character, which might confused the plugin here's an updated version of your config with the changes I mentioned above: https://mega.nz/file/ok13EBTL#X6MV5kjtl3sQxkb6aFaiMqmMVuaH06oHGNq9fLNkfBk
