### ISSUE TITLE
Hearts get reset when server restarts

### ISSUE THREAD

**Issue by Animationking11** [GamerDuck123/LifeStealSMP#4]
Video of issue: https://youtu.be/AjmQrc1kZoI

**Comment by Animationking11** [comment]
As you can see in the video my heart is gone after restart

**Comment by Animationking11** [comment]
When will this be fixed? @GamerDuck123

**Comment by GamerDuck123** [comment]
I've been unable to recreate this issue, are you able to contact me on discord @ GamerDuck123#9999 to discuss more?

If not we can continue here, I'm just slower to respond on here!

What other plugins do you have installed?
Are you using MySQL or SQLite?
Are there any errors? If so can you post them?
Can you send a copy of your config.yml?

This would all help me try and figure out what the problem is as I cannot figure it out! Thank you!

**Comment by Animationking11** [comment]
@GamerDuck123 Ok I sent you a friend request my discord is !Odd#9999
